Export parsed tag body as an output
cockpit-project/action-release pull request #1
Opened 2022-06-01 13:57 UTC by martinpitt

2022-06-02 11:53 UTC, allisonkarlitskaya requested changes

2022-06-02 11:53 UTC, allisonkarlitskaya commented on action.yml
> +    description: "Tag details without the Subject"
This capital S is funny.

2022-06-02 11:53 UTC, allisonkarlitskaya commented on action.yml
> +    value: ${{ steps.publis.outputs.body }}
`publis`?

2022-06-03 08:28 UTC, martinpitt commented on action.yml
> +    description: "Tag details without the Subject"
Fixed.

2022-06-03 08:28 UTC, martinpitt commented on action.yml
> +    value: ${{ steps.publis.outputs.body }}
Ouch! Fixed.

2022-06-03 08:39 UTC, allisonkarlitskaya approved these changes
Thanks.  Looking forward to using this.

2022-06-03 10:01 UTC, merged